//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "www.algonquincollege.com/onlineservice/reviews", IsNullable = false)]
public partial class restaurants
{

    private restaurantsRestaurant[] restaurantField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("restaurant")]
    public restaurantsRestaurant[] restaurant
    {
        get
        {
            return this.restaurantField;
        }
        set
        {
            this.restaurantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurant
{

    private string nameField;

    private string logoField;

    private restaurantsRestaurantImage imageField;

    private restaurantsRestaurantPhone phoneField;

    private restaurantsRestaurantLocation locationField;

    private string summaryField;

    private string reviewerField;

    private restaurantsRestaurantRating ratingField;

    private restaurantsRestaurantReview_date review_dateField;

    private restaurantsRestaurantItem[] menuField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string logo
    {
        get
        {
            return this.logoField;
        }
        set
        {
            this.logoField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantImage image
    {
        get
        {
            return this.imageField;
        }
        set
        {
            this.imageField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantPhone phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantLocation location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }

    /// <remarks/>
    public string summary
    {
        get
        {
            return this.summaryField;
        }
        set
        {
            this.summaryField = value;
        }
    }

    /// <remarks/>
    public string reviewer
    {
        get
        {
            return this.reviewerField;
        }
        set
        {
            this.reviewerField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantRating rating
    {
        get
        {
            return this.ratingField;
        }
        set
        {
            this.ratingField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantReview_date review_date
    {
        get
        {
            return this.review_dateField;
        }
        set
        {
            this.review_dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
    public restaurantsRestaurantItem[] menu
    {
        get
        {
            return this.menuField;
        }
        set
        {
            this.menuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantImage
{

    private string image_nameField;

    private restaurantsRestaurantImageImage_size image_sizeField;

    /// <remarks/>
    public string image_name
    {
        get
        {
            return this.image_nameField;
        }
        set
        {
            this.image_nameField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantImageImage_size image_size
    {
        get
        {
            return this.image_sizeField;
        }
        set
        {
            this.image_sizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantImageImage_size
{

    private byte image_widthField;

    private byte image_heightField;

    private string dimensionField;

    /// <remarks/>
    public byte image_width
    {
        get
        {
            return this.image_widthField;
        }
        set
        {
            this.image_widthField = value;
        }
    }

    /// <remarks/>
    public byte image_height
    {
        get
        {
            return this.image_heightField;
        }
        set
        {
            this.image_heightField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dimension
    {
        get
        {
            return this.dimensionField;
        }
        set
        {
            this.dimensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantPhone
{

    private ushort area_codeField;

    private string numberField;

    /// <remarks/>
    public ushort area_code
    {
        get
        {
            return this.area_codeField;
        }
        set
        {
            this.area_codeField = value;
        }
    }

    /// <remarks/>
    public string number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantLocation
{

    private string addressField;

    private string cityField;

    private string postal_codeField;

    private string provinceField;

    /// <remarks/>
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    public string postal_code
    {
        get
        {
            return this.postal_codeField;
        }
        set
        {
            this.postal_codeField = value;
        }
    }

    /// <remarks/>
    public string province
    {
        get
        {
            return this.provinceField;
        }
        set
        {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantRating
{

    private string typeField;

    private byte min_valueField;

    private byte max_valueField;

    private byte valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min_value
    {
        get
        {
            return this.min_valueField;
        }
        set
        {
            this.min_valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte max_value
    {
        get
        {
            return this.max_valueField;
        }
        set
        {
            this.max_valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public byte Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantReview_date
{

    private ushort yearField;

    private string monthField;

    private byte dayField;

    /// <remarks/>
    public ushort year
    {
        get
        {
            return this.yearField;
        }
        set
        {
            this.yearField = value;
        }
    }

    /// <remarks/>
    public string month
    {
        get
        {
            return this.monthField;
        }
        set
        {
            this.monthField = value;
        }
    }

    /// <remarks/>
    public byte day
    {
        get
        {
            return this.dayField;
        }
        set
        {
            this.dayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantItem
{

    private string nameField;

    private restaurantsRestaurantItemPrice priceField;

    private restaurantsRestaurantItemBulk_price bulk_priceField;

    private string typeField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantItemPrice price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    public restaurantsRestaurantItemBulk_price bulk_price
    {
        get
        {
            return this.bulk_priceField;
        }
        set
        {
            this.bulk_priceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantItemPrice
{

    private string currencyField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "www.algonquincollege.com/onlineservice/reviews")]
public partial class restaurantsRestaurantItemBulk_price
{

    private byte min_qtyField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min_qty
    {
        get
        {
            return this.min_qtyField;
        }
        set
        {
            this.min_qtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
